### ISSUE TITLE
Error facing docker installation locally

### ISSUE THREAD

**Issue by Toredevir** [CybercentreCanada/assemblyline#114]
After locally installing ASL following "https://cybercentrecanada.github.io/assemblyline4_docs/installation/appliance/docker/", I was faced with incorrect credentials. 

**Environment :**
Ubuntu 22.04.3

**Fix**
To fix it I needed to run this command at the very beginning of Docker installation. Which I did not find anywhere in the walk-through.

sudo apt install python3-pip -y
pip3 install pip -U
sudo pip install assemblyline_client
Proceed with Docker installation from link above.

**Comment by cccs-rs** [comment]
Not sure I understand how installing the Assemblyline's Python client on the host would fix an invalid credentials error.

What's likely to have happened is if you tried to login before the [bootstrap container](https://github.com/CybercentreCanada/assemblyline-docker-compose/blob/1733057d7070a5ff64e70e6b429f6817e262ce31/minimal_appliance/bootstrap-compose.yaml#L5) initialized the admin account (which there can be a delay depending on how long it takes the dependencies to achieve a ready state), you would've encountered the invalid login error because the account doesn't exist in the system.

Can you provide more details if that wasn't the case?

**Comment by cccs-rs** [comment]
Any updates on this issue?

**Comment by cccs-rs** [comment]
Will close the issue. If there are any updates or if this issue still persists, feel free to re-open.
