### ISSUE TITLE
GPG-encrypted files

### ISSUE THREAD

**Issue by cccs-rs** [CybercentreCanada/assemblyline#126]
**Is your feature request related to a problem? Please describe.**
[Discord](https://discord.com/channels/908084610158714900/908717441771794472/1167236225938243687): ... _Currently trying to play with a sample from this [campaign](https://www.bleepingcomputer.com/news/security/fake-keepass-site-uses-google-ads-and-punycode-to-push-malware/) and it uses a GPG encrypted next-stage payload_

**Describe the solution you'd like**
To be able to decrypt the file downloaded using GPG within Extract (or perhaps in another service if that's more appropriate?)

**Additional context**
Related to: https://github.com/CybercentreCanada/assemblyline/issues/125

**Comment by gdesmar** [comment]
[GPG file](https://www.virustotal.com/gui/file/8a2639de6c5ce59b4e8d048616b25b681b3a08715a92184334d07dbdd2b006ea) and the password for the file is "pendosi". OverPower should add it to the list of possible password since #125.

I need to add some Identify magic pattern to handle GPG files. I think we can handle public keys, private keys, symmetrically encrypted data and RSA encrypted session key. That should be a good start for GPG identification in AL.

**Comment by gdesmar** [comment]
Idenfication of gpg/pgp files: https://github.com/CybercentreCanada/assemblyline-base/pull/1413
GPG symmetric files handling in Extract: https://github.com/CybercentreCanada/assemblyline-service-extract/pull/240
Starting with Extract 4.4.0.stable27, this will work!
