### ISSUE TITLE
Empty/failing update source can cause infinite loops of retires

### ISSUE THREAD

**Issue by kam193** [CybercentreCanada/assemblyline#141]
**Describe the bug**
When processing an update source that fails and does not produce any data, the update process is immediately restarted. If it happens during a regular update, the process is started again for all sources. It causes unnecessary CPU usage, but may also exhaust some rate limiting or stop a service from starting (if it waits for the updates to be done).

**To Reproduce**
1. Choose a service and configure a new update source that will fail during processing.
2. For example, choose a YARA service and add the source: https://github.com/Neo23x0/signature-base (or just craft a source that will cause yara to fail)
4. Observe the updater logs.
5. After downloading a new update source, it will fail to import the file and retry.
6. After a few seconds/minutes, you will see that the updating process is looped.

Note: Previously, I managed to enable debug logging and saw some comments that the `<update_dir>/<source_name>/` is missing. For some reason, my setup doesn't want to respect debug log settings now, so I cannot ensure - but it may be important as then the reproduction may not work for existing sources.

Note2: I think that regex filtering out all data should also work as a reproduce.

**Expected behavior**
1. Only the failed source should be retried, not all.
2. Retries should be limited and delayed.

**Screenshots**

**Environment (please complete the following information if pertinent):**
 - Assemblyline Version: 4.4.0.stable79

**Additional context**
In this case, filtering not-supported rules with a regex doesn't work as a workaround, but it's a thing for another issue.

**Comment by cccs-rs** [comment]
A part of the [inventory check](https://github.com/CybercentreCanada/assemblyline-v4-service/blob/master/assemblyline_v4_service/updater/updater.py#L314-L319) function should cause it to only retry missing sources. Each service can define their inventory check in different ways but I believe YARA should be following the default behaviour.

As for imposing a retry limit or delay, this is something that we could add.

**Comment by cccs-rs** [comment]
Hi there! We currently have a bunch of services with dev releases that should have a patch to resolve this. 
Would you mind testing it out on your deployment? Since you mentioned YARA, version 4.4.1.dev44 would be a good test candidate.

**Comment by kam193** [comment]
Hi, unfortunately, I don't have any working environment with configured to use dev branch currently - if I find time, I'll set up one and test.

BTW, I have also noticed that sometimes (after recreating update container, and creating a new service instance at the same time?), AL seems to trigger updates twice almost at the same time. My impression was that they were processed concurrently, but maybe they were just shortly after each other. Effectively slowing down starting the service as it was first waiting for the update container to be ready & getting first updates, and shortly after that getting a new update. Does it sound true, or have I observed it wrongly?

**Comment by cccs-rs** [comment]
Sounds like you're talking about when the updater starts up, it first performs a local update check (basically checks to see if we already have data that we can send to the service instance ie. previous imported signatures) and then the source update check (where it tries to pull from the external sources).

Usually if a service is configured to `wait_for_update`, then what should happen is that the updater is started first and upon having a bundle it can send to services, it will tell Scaler that the service instance is ready to be scaled. If let's say an updater doesn't have anything to send to a service from the local update check (ie. Signatures index is wiped or nothing cached in persistent storage), then it should tell the Scaler that the service shouldn't be scaled up at all (because otherwise, why would you `wait_for_update`?):
https://github.com/CybercentreCanada/assemblyline-v4-service/blob/1c557fec76efbc2f09040444912d34b40a2fcf13/assemblyline_v4_service/updater/updater.py#L277

At least based on what you described, that's what it sounds like but I could be off the mark 😅

**Comment by cccs-rs** [comment]
That should actually be resolved in this PR:
https://github.com/CybercentreCanada/assemblyline-v4-service/pull/719

What happened was the the local thread would do it's inventory check and task the source thread to perform updates (if it deemed data from sources are missing), but it only gave it 60s until the next check. So if the source thread didn't finish what it needed to do within that span, then the local thread would keep re-tasking the source thread (depending on the conditions of the inventory check).

I've only really noticed the issue in ConfigExtractor because of venv creation so I can imagine it can happen to other services that take a long time to process the file(s) from a source.

**Comment by cccs-rs** [comment]
Should be resolved in the latest release. If the issue still persists, feel free to reopen the issue 😀
