### ISSUE TITLE
Feature Request: Interactive LLM Integration in Assemblyline via Configurable UI Button

### ISSUE THREAD

**Issue by ociappara** [CybercentreCanada/assemblyline#183]
In the detailed results page of Assemblyline, it would be beneficial to have a button that can be configured to connect with our instance of ChatGPT. As Large Language Models (LLMs) become increasingly prominent, integrating them into Assemblyline could greatly assist analysts in summarising the information the system extracts. This feature would also enable users to ask questions directly within the system. While the initial summarisation process could be done as a service using tags, incorporating an interactive UI element offers greater flexibility and is likely a more useful to analysts, and gives the LLM access to the entire results not just tags.

I would also be curious if these functionalities could be added dynamically through configurations and standalone Docker containers. This approach would allow for more customisation of Assemblyline while maintaining alignment with the main repository. This flexibility would allow us to expand Assemblyline without compromising the integrity of the core platform.

**Comment by cccs-sgaron** [comment]
Looks like good timing to me! What I have planned so far is the following:

1. Button in the file viewer to sumarize code
2. Quick summary of the overall findings in the submission details
3. Quick summary of the results of a given file in the file details
4. Hybrid AI/predefined report where the AI would summarized the findings and explain the results of each service then the important IOC / Files would be listed at the bottom.

Right now, I have the code written in a way where you can define your own system prompts and your own parameters to pass to the AI. The code is written in a way that it should work with most AI API but its only been tested with OpenAI chat/completions API. 

We have no plan just yet for the user to ask question to the AI but we're also not ruling this out. This will probably come as a future update.

Here are the PRs for this patch:
https://github.com/CybercentreCanada/assemblyline-base/pull/1522
https://github.com/CybercentreCanada/assemblyline-ui/pull/822
https://github.com/CybercentreCanada/assemblyline-ui-frontend/pull/914

Here's a sneak peak of what the code summarization output looks so far: 
![image](https://github.com/CybercentreCanada/assemblyline/assets/59840781/f98ebeed-a615-4149-bc7e-d60599b741ce)

**Comment by ociappara** [comment]
This is great! Our data science team is interested in collaborating on this! <3

**Comment by cccs-sgaron** [comment]
The first pass for the AI integration is mostly done. I'd say this is in a good enough state to be usable right now and the limitations are mostly due to the kind of model you use, the number of token the model is able to analyse and the prompt use to query the model. 

Our default implementation has decent result with the prompt that we've configured as default. At this point, we will probably need some help to fine tune the prompt to get better results. So on top of the code Analysis that we had before we now have:

The AI summarize and explain in detail the AL output in an AI generated report
![image](https://github.com/CybercentreCanada/assemblyline/assets/59840781/0aa2649e-0f63-44f4-9b67-e98b140af6a0)
![image](https://github.com/CybercentreCanada/assemblyline/assets/59840781/7be18b47-dfdc-4bbe-93ad-b6a11ea71ce9)

The AI creating an executive summary for both the submission and the file details
![image](https://github.com/CybercentreCanada/assemblyline/assets/59840781/082d30f9-396f-4ad4-be2f-e1b71d0c67bb)

So this covers all the of originally defined scenarios. You can play with this in the most recent Dev build (4.4.1.dev389+)

**Comment by ociappara** [comment]
Thank you @cccs-sgaron can you help me with the values to enable it please?

```
  ui:
    ai:
      enabled: true
      chat_url: "http://ai:5000"
```

**Comment by cccs-sgaron** [comment]
I'm working on the doc now will push it sometimes today
