### ISSUE TITLE
Getting badlisted tags

### ISSUE THREAD

**Issue by kam193** [CybercentreCanada/assemblyline#189]
**Is your feature request related to a problem? Please describe.**
I have a service marking files based on the similarity. Currently, it uses a static hashes list. I'd like to make it more dynamic by including files badlisted in AL. However, when it's possible to get a list of safelisted tags, the badlist client & API offers just a lookup service.

**Describe the solution you'd like**
I'd like to get access to get badlist for specific tags as it is for [the safelist](https://github.com/CybercentreCanada/assemblyline-v4-service/blob/9c111eb67a9bf5a6eee813df5a40c354ac20b8ce/assemblyline_v4_service/common/api.py#L107).

**Describe alternatives you've considered**
Alternatively, I could probably just query ES directly, if you don't see a reason to include such a method.

**Additional context**

**Comment by cccs-sgaron** [comment]
As I was designing the badlist, I intentionally did not add that feature because I realised this will cause a very bad issue to the DB. In fact, it is on my todo list to remove that feature from the safelist. The reason behind this is that this call can end up downloading multiple millions of hashes and causing considerable slow down to the database. It is much better to issue a batch of hashes/tags for elastic to check if they are safe or not then downloading the whole list and checking locally. The only reason the safelist has not killed the DB yet with such bad practice is that we don't have a list of millions of safe tags and all tags are added manually. 

I would strongly advise you to reconsider the design of such service to issue lookups to the DB instead of downloading the full set of hashes as this will be definitely more efficient.

**Comment by kam193** [comment]
Hey, I understand your point of view and have it in mind, however it's not so easy: the goal is to find similar (TLSH), not the same hashes, and last time when I was looking for that, the ES support for such a use case was very limited.

But I have the same concern you pointed out, and after initial PoC I have decided that it still should be enough for my use case (the most important limitations: I do not plan to have millions of hashes, but to - as in your use case with safelist - manually add them ;)), but just to be clear, I plan to separately cache downloaded hashes & update them periodically.

Thanks for the comment and the recommendations!

**Comment by cccs-sgaron** [comment]
You can actually directly search for TLSH. In fact, if you add all the TLSH into badlist, it will do the search for you. Also you can use the approximated search in elastic and that should give you good results. 

tlsh:T1234...4321~

**Comment by kam193** [comment]
Hmm, I'll then look again for that - this is exactly what I was looking for & my initial plan, but a few months ago I'm sure I didn't find the right way to do it in the ES. Thanks!
