### ISSUE TITLE
Feature Request: (Badlist) Show which badlist source was matched against in the heuristics.

### ISSUE THREAD

**Issue by simonbjorzen-ts** [CybercentreCanada/assemblyline#192]
**Is your feature request related to a problem? Please describe.**
It would be helpful to see which badlist source was matched against in the heuristic.
Right now it only shows 'IOC' tag was found in the list of bad IOCs.

**Describe the solution you'd like**
Extra metadata for the match, perhaps a KEY_VALUE field with the following data:

**IOC:** 'Example IOC'
**Source:**: 'Badlist Name'
**Added on:**: 'Timestamp'

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by simonbjorzen-ts** [comment]
Perhaps the attribution field can be used for this? 
I didn't see that before making this issue.

**Comment by cccs-rs** [comment]
We may not be able to show all the metadata associated to a badlist match in the way you described (in a single section) as the reasons can vary and can be classified at different levels, in which case we'd have to split up the reasoning as a subsection of the IOC hit (something we currently do now but the presentation can be improved).

In regards to metadata such as "Added On" (`added`) and "Last Updated" (`updated`), we can add that metadata for context since it's behind the classification of the badlist item itself but we aren't able to distinguish between when one source "added" the item vs another: we just know when it was added/updated to the system in general but not by whom.

**Comment by cccs-rs** [comment]
Should be part of the 4.5 release of Assemblyline:
https://github.com/CybercentreCanada/assemblyline/releases/tag/v4.5.0.stable1
