### ISSUE TITLE
Frontend crashes when right clicking on any tag 

### ISSUE THREAD

**Issue by sgaron-msft** [CybercentreCanada/assemblyline#282]
**Describe the bug**
When viewing submission or file details, right clicking on any tags causes the UI to crash with the following error message: "**_d.ui.api_proxies.includes is not a function_**"

**To Reproduce**
1. View any submissions with generated tags
2. Right click on a tag
3. See a bug crawling on your screen!

**Expected behavior**
I expect to see the context menu related to the tag.

**Screenshots**
![image](https://github.com/user-attachments/assets/99d3fc9b-88f8-468e-81aa-0409d1620496)

**Environment (please complete the following information if pertinent):**
 - Assemblyline Version: 4.5.0.57
 - Browser: Edge and Chrome

**Additional context**
We have no api_proxies values defined in our configuration. When the whoami API is called, the API returns an empty dictionary.

**Comment by cccs-rs** [comment]
Is this issue still ongoing? Taking a look at the frontend code at the moment and it doesn't look like it should encounter that error even when `ui.api_proxies: []`.

But maybe I'm missing a certain condition on when the bug is raised, currently looking at any calls involving `api_proxies.includes()`

**Comment by sgaron-msft** [comment]
Seems fine now. There must have been a new built since this ticket was publish that fixed it.
