### ISSUE TITLE
Resubmit - Ignore Cache on "Use the same parameters"

### ISSUE THREAD

**Issue by eljeffeg** [CybercentreCanada/assemblyline#59]
When you do a Resubmit using `Use the same parameters`, I think you should also add `Ignore result cache`.  Otherwise you're not really resubmitting it.  You're just pulling up the cache report of the prior submission, which you were already viewing.  In the original submission, there likely wasn't a cache to ignore.  So the system's state has changed and I think the resubmit needs to account for that.  I think the likely user intent here would be to actually run the submission again against those services.

**Comment by cccs-sgaron** [comment]
I do not agree with you on this one, services should produce prediactable results so if their version did not change, their output should not. If that is not the case, it should be fixed. But assuming that is the case, there are no valid reason to set ignore cache as it would just lead to the same results than the cache anyway. And if the service did change, than the cache would not be valid.

**Comment by eljeffeg** [comment]
Wouldn't these be some reasons a service of the same version could produce a different result on a rerun?

1) The source updates have imported new signatures.
2) External hash lookups or services might produce new results.
3) The service had an error (like memory usage), but the destruction / creation of the service pod resolved it (this was my case)
4) You've updated your system safelist or some other service in the chain that effects the output of other services.

I'm sure more could potentially be thought of.  Yes, all things being equal, it shouldn't matter.  But I can say it mattered in my case and it was frustrating until I figured out the reason.

**Comment by eljeffeg** [comment]
@cccs-sgaron @cccs-douglass @cccs-rs I wanted to follow up this week to see if the above situations would produce valid non-predictable results.   I'm fine with accepting a `wontfix` and will move on, but just wanted to make sure you were able to review and consider these possibilities.  Thumbs up, Thumbs down, comment.. just want to make sure I close the loop on the conversation.

**Comment by cccs-rs** [comment]
Hi @eljeffeg 

> Below are some reasons I think a service of the same version may produce a different result on a rerun.
> 
> * The source updates have imported new signatures.

In cases like these, the source updates should be rolled into the tool version (See: https://github.com/CybercentreCanada/assemblyline-v4-service/blob/6fd22a62fa7c5856e3b1ff962fe147f446295fd8/assemblyline_v4_service/common/base.py#L155), so even through the service version itself didn't change, the dependencies did and that should be reflected in the results + caching
> * External hash lookups or services can produce new results.

This is a valid scenario, however similar to the first point, if you can squeeze in versioning in the results, that could help without having to ignore the cache 😅 or marking the service to ignore cache should also account for this (I think)
> * The AL service had an error (like memory usage), but the destruction / creation of the service pod resolved it (this was my case)

This one is kind of double-sided: on the one hand it's not a true result, it's just the byproduct of an error so it should be allowed to run again or the result ignored entirely from the original run. BUT on the other hand, we're also not sure if a particular file will constantly fail for a service version regardless of configuration until a new service version is released. So if the particularly troublesome file appears repeatedly, we wouldn't want to resend that file to the service if we know there's going to be a problem and there's nothing we can do about it (especially if this could cause a system backlog in processing).
> * Admin updated the system safelist, env, config, or some other indirect service that effects the output of the selected services.

I believe service configuration (or maybe just the params) is used in the cache key for results, not sure if it factors safelist or container configurations 

To @cccs-sgaron's point, with what I've commented on, there are better ways to resolve these kind of scenarios without having to bring forward 'ignore cache' on resubmit

**Comment by cccs-sgaron** [comment]
My fault to not have provided enough context on this one. Here are some things to consider that should be implemented on all services: 

- Service errors are not cached, that is part of service base so it is taken care of for all services
- Service should not report errors as a result section
- Service updates must invalidate the cache, all services that have an updater should alter the tool version (Just like @cccs-rs  said in his exemple)
- If a service does a hash lookup and the external service does not provide a version, the service should set "disable_cache:true" in its manifest because caching is impossible
- Configuration params are part of the service configuration hash so any changes do invalidate the hash, this is taken care by service base also

If you see any service that do not behave like this, it is important to tell us and if you build more services it is important that they follow those rules. 

As a general rule of thumb, if you use any of the submission parameters that start with "ignore" (ignore_filtering, ignore_cache, ignore_dynamic_recursion_prevention...), your basically just bypassing the problem. We should instead try to find out why you had to use this parameter and find a way to fix things so you don't have to.

**Comment by eljeffeg** [comment]
Thanks for the explanation.  This now makes a lot more sense to me.
