### ISSUE TITLE
Incorrect file.parent in ontology result

### ISSUE THREAD

**Issue by ed4wg** [CybercentreCanada/assemblyline#64]
**Describe the bug**
The `file.parent` element in the ontology result points to the root file of the submission rather than the actual parent.

**To Reproduce**
Take a file that has child files extracted, and further children extracted from those files so you have a hierarchy 3 or more deep. When retrieving the ontology results for that submission via `/api/v4/ontology/submission/<sid>`, the `file.parent` element of a level 2 or more child file is specifying the root file hash of the submission rather than the actual parent of the extracted file.

**Expected behavior**
The `file.parent` element of an ontology result should point to the direct parent of that file.

**Comment by cccs-rs** [comment]
If memory serves, this was a design decision as services aren't aware of the parent of a file and that a file, even within the same submission, could have multiple parents (and currently the model assumes there's a single parent per file).

Since this information is populated by the API, we opt'd to use the absolute parent (root/submitted file) to avoid putting unnecessary strain on the API containers.

**Comment by ed4wg** [comment]
Perhaps the property name should be something other than `file.parent` to avoid confusion. Maybe `file.submissionrootparent` or something like that?

**Comment by cccs-rs** [comment]
Perhaps, although if that were the case, it would probably go into the `submission` block rather than the `file` block and be called `root_file` or `submitted_file`?

(Just thinking aloud 😅)

**Comment by ed4wg** [comment]
yeah that makes more sense :)
