### ISSUE TITLE
PE Service throws exception - AttributeError: 'NoneType' object has no attribute 'remove_all_relocations'

### ISSUE THREAD

**Issue by ociappara** [CybercentreCanada/assemblyline#80]
**Describe the bug**
 File "/var/lib/assemblyline/.local/lib/python3.9/site-packages/assemblyline_v4_service/common/base.py", line 169, in handle_task
    self.execute(request)
  File "/opt/al_service/pe/pe.py", line 1844, in execute
    out_data = unmapper.unmap(self.binary, in_data)
  File "/opt/al_service/pe/unmapper.py", line 54, in unmap
    unmapped.remove_all_relocations()
AttributeError: 'NoneType' object has no attribute 'remove_all_relocations'

Scan - 44d965e096e4dfb2b35e66fc3bd31b1b7874a89b24813b524fb4d2e818aaa50d from VT

**Comment by gdesmar** [comment]
We found a few other samples that are causing the same problem, but they are all corrupted. VirusTotal is confirming that fact, and it doesn't look like we can try to recreated a closer representation of the original PE with the unmapper. I wrapped the unmapper code in a try and will look for that error so that it doesn't stop us from showing the rest of the information that we can get out.

Here is the list of files that were causing the same problem, in case someone wants to investigate those more:
- 1040f30bd46618293e15c6bc94ac401b5c1cc08dc24042b502b8b66a65cf72b2 
- 22dd8463381c8be2aad047b01988f093eb94bed489aafc14c3d46b846aa018ab
- 2bc2bec3ad898793c36866f6f2c7e42bf2328e7c0d9b528dbd403f668ca8a4aa
- 4134aa38f2f882cfa345fdb1631f9e84d7976c7c833e28682f0bc7f5ea9a906b
- 49656f62649d8c88e90dcdf96699084b37d5c60a6fb476b790918a7e48e7851e
- 7e92d70a9d4d5bb3d248babce8e25cd200436e73c0d007ad91ee0e7238d143d1
- 82c5b1390d9b77d8fdf3da05974a931f327b66f9e3789a4049d80fdc7dc5a99f
- a95f1fefd5e7fa6ae5c73264c2e7c5cd761cd1f5475febf64b6243d536eaf024
- aa898087cd3503d7ebf0b189651e731fdc4e6aada6ba43e568a3acf95f499efb
- ae182d5df5c0cad3c76665949c94c404e65554aafa7508d403c2112fbe4dbbf3
- bec4c88c3cc728e155c9ee301293f17c67ee7eeffb0b2227db59db15579777ce
- d75f790b42c9b9e124388c5fde58a77b06321ea7ad974f234f7c3ac6ce264398
- e36391f8af503394154c338fce499594de44522528281c4b6657410c0f026826
- f7f0233c18feb2b582fd90dff7a416addab3e1259e4e6c1ee31968f37793f391
